apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-sleeper
  template:
    metadata:
      labels:
        app: ubuntu-sleeper
    spec:
      containers:
      - name: ubuntu-sleeper
        image: hsmtkk/refactored-octo-train:ubuntu-sleeper
        args: ["10"]
